adminapp/urls.py
from django.urls import re_path

import adminapp.views as adminapp

from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),
    re_path(r"^users/create/$", adminapp.user_create, name="user_create"),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.user_update, name="user_update"),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.user_delete, name="user_delete"),
    re_path(r"^categories/create/$", adminapp.ProductCategoryCreateView.as_view(), name="category_create"),
    re_path(r"^categories/read/$", adminapp.categories, name="categories"),
    re_path(r"^categories/update/(?P<pk>\d+)/$", adminapp.ProductCategoryUpdateView.as_view(), name="category_update"),
    re_path(r"^categories/delete/(?P<pk>\d+)/$", adminapp.ProductCategoryDeleteView.as_view(), name="category_delete"),
    re_path(r"^products/create/category/(?P<pk>\d+)/$", adminapp.product_create, name="product_create"),
    re_path(r"^products/read/category/(?P<pk>\d+)/$", adminapp.products, name="products"),
    re_path(r"^products/read/(?P<pk>\d+)/$", adminapp.ProductDetailView.as_view(), name="product_read"),
    re_path(r"^products/update/(?P<pk>\d+)/$", adminapp.product_update, name="product_update"),
    re_path(r"^products/delete/(?P<pk>\d+)/$", adminapp.product_delete, name="product_delete"),
]

best_shop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, re_path

import mainapp.views as mainapp
# import ordersapp.views as orders

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^products/", include("mainapp.urls", namespace="products")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    path("", include("social_django.urls", namespace="social")),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    re_path(r"^order/", include("ordersapp.urls", namespace="ordersapp")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.products, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.products, name="category"),
    re_path(r"^product/(?P<pk>\d+)/$", mainapp.product, name="product"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.products, name="page"),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authnapp.forms import ShopUserEditForm
from authnapp.models import ShopUser
from mainapp.models import Product, ProductCategory


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ProductCategoryEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = ProductCategory
        fields = "__all__"


class ProductEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = Product
        fields = "__all__"

adminapp/views.py
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from adminapp.forms import ProductCategoryEditForm, ProductEditForm, ShopUserAdminEditForm
from authnapp.forms import ShopUserRegisterForm
from authnapp.models import ShopUser
from mainapp.models import Product, ProductCategory


@user_passes_test(lambda u: u.is_superuser)
def admin_main(request):
    response = redirect("admin:users")
    return response


class UsersListView(LoginRequiredMixin, ListView):
    model = ShopUser
    template_name = "adminapp/users.html"


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = "пользователи/создание"

    if request.method == "POST":
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse("admin:users"))
    else:
        user_form = ShopUserRegisterForm()

    content = {"title": title, "update_form": user_form, "media_url": settings.MEDIA_URL}

    return render(request, "adminapp/user_update.html", content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = "пользователи/редактирование"

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == "POST":
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("admin:user_update", args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    content = {"title": title, "update_form": edit_form, "media_url": settings.MEDIA_URL}

    return render(request, "adminapp/user_update.html", content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = "пользователи/удаление"

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == "POST":
        # user.delete()
        # Instead delete we will set users inactive
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse("admin:users"))

    content = {"title": title, "user_to_delete": user, "media_url": settings.MEDIA_URL}

    return render(request, "adminapp/user_delete.html", content)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = "админка/категории"
    categories_list = ProductCategory.objects.all()
    content = {"title": title, "objects": categories_list, "media_url": settings.MEDIA_URL}
    return render(request, "adminapp/categories.html", content)


class ProductCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ProductCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"


class ProductCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ProductCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        context["title"] = "категории/редактирование"
        return context


class ProductCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ProductCategory
    template_name = "adminapp/category_delete.html"
    success_url = reverse_lazy("admin:categories")
    foo = "BAR"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = "админка/продукт"
    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by("name")
    content = {"title": title, "category": category, "objects": products_list, "media_url": settings.MEDIA_URL}
    return render(request, "adminapp/products.html", content)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = "продукт/создание"
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse("admin:products", args=[pk]))
    else:
        # set initial value for form
        product_form = ProductEditForm(initial={"category": category})

    content = {"title": title, "update_form": product_form, "category": category, "media_url": settings.MEDIA_URL}
    return render(request, "adminapp/product_update.html", content)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "adminapp/product_read.html"


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = "продукт/редактирование"
    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("admin:product_update", args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {
        "title": title,
        "update_form": edit_form,
        "category": edit_product.category,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "adminapp/product_update.html", content)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    title = "продукт/удаление"
    product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse("admin:products", args=[product.category.pk]))

    content = {"title": title, "product_to_delete": product, "media_url": settings.MEDIA_URL}
    return render(request, "adminapp/product_delete.html", content)

adminapp/templates/adminapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}

</head>

<body>

    {% include 'adminapp/includes/inc_menu.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    </div>

</body>

</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
<p>
<div class="row justify-content-end">
    <div class="col-2">
        <a href="{% url 'admin:category_create' %}" class="btn btn-outline-secondary btn-sm" role="button"
            aria-pressed="true"><i class="fa fa-plus" aria-hidden="true"></i> Добавить</a>
    </div>
</div>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название категории</th>
            <th scope="col">Товары категории</th>
            <th scope="col">Описание</th>
            <th scope="col" colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for object in objects %}
        <tr id="{{ object.pk }}" {% if not object.is_active %}style="opacity: 30%;" {% endif %}>
            <th scope="row">{{ object.pk }}</th>
            <td>{{ object.name|title }}</td>
            <td><a href="{% url 'admin:products' object.pk %}"><i class="fa fa-angle-right" aria-hidden="true"></i> К
                    списку</a></td>
            <td>{{ object.description|title }}</td>
            <td><a href="{% url 'admin:category_update' object.pk %}"><i class="fa fa-pencil"
                        aria-hidden="true"></i></a></td>
            <td><a href="{% url 'admin:category_delete' object.pk %}"><i class="fa fa-trash-o"
                        aria-hidden="true"></i></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
<p>
<div class="row justify-content-center">
  <div class="col-6">
    <h3>Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?</h3>
    <form action="{% url 'admin:category_delete' object.pk %}" method="post">
      {% csrf_token %}
      <p>
      <div class="row justify-content-around">
        <div class="col-5">
          <a href="{% url 'admin:categories' %}" class="btn btn-outline-secondary btn-block" role="button"
            aria-pressed="true">Отмена</a>
        </div>
        <div class="col-5">
          <button type="submit" class="btn btn-outline-danger btn-block">Удалить</button>
        </div>
      </div>
      </p>
    </form>
  </div>
</div>
</p>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="row justify-content-md-center">
  <div class="col-7">
    <p>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-outline-primary btn-block">Сохранить</button>
    </form>
    </p>
    <p>
      <a href="{% url 'admin:categories' %}" class="btn btn-outline-secondary btn-block" role="button"
        aria-pressed="true">К списку категорий</a>
    </p>
  </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
<p>
<div class="row justify-content-center">
  <div class="col-6">
    <h3>Уверены, что хотите удалить продукт <strong>{{ product_to_delete.name }}</strong>?</h3>
    <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
      {% csrf_token %}
      <p>
      <div class="row justify-content-around">
        <div class="col-5">
          <a href="{% url 'admin:products' product_to_delete.category.pk %}" class="btn btn-outline-secondary btn-block"
            role="button" aria-pressed="true">Отмена</a>
        </div>
        <div class="col-5">
          <button type="submit" class="btn btn-outline-danger btn-block">Удалить</button>
        </div>
      </div>
      </p>
    </form>
  </div>
</div>
</p>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
<p>
<div class="row">
  <div class="col-6">
    <h3>Продукт <strong>{{ object.category.name|title }} | {{ object.name|title }}</strong></h3>
  </div>
</div>
</p>
<p>
<div class="row">
  <div class="col-9">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Характеристика</th>
          <th scope="col">Значение</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Цена (руб.)</th>
          <td>{{ object.price }}</td>
        </tr>
        <tr>
          <th scope="row">Количество</th>
          <td>{{ object.quantity }}</td>
        </tr>
        <tr>
          <th scope="row">В каталоге</th>
          <td>{% if object.is_active %}да{% else %}нет{% endif %}</td>
        </tr>
        <tr>
          <th scope="row">Краткая информация</th>
          <td>{{ object.short_desc }}</td>
        </tr>
        <tr>
          <th scope="row">Подробная информация</th>
          <td>{{ object.description }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-3">
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}"
      style="max-width: 100%;">
  </div>
</div>
</p>
<p>
<div class="row justify-content-around">
  <div class="col-4">
    <a href="{% url 'admin:products' object.category.pk %}" class="btn btn-outline-primary" role="button"
      aria-pressed="true">К списку товаров</a>
  </div>
  <div class="col-4">
    <div class="btn-group col-12" role="group" aria-label="Basic example">
      <a href="{% url 'admin:product_update' object.pk %}" class="btn btn-outline-secondary col-6" role="button"
        aria-pressed="true">Редактировать</a>
      <a href="{% url 'admin:product_delete' object.pk %}" class="btn btn-outline-danger col-6" role="button"
        aria-pressed="true">Удалить</a>
    </div>
  </div>
</div>
</p>
{% endblock content %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="row justify-content-md-center">
  <div class="col-7">
    <p>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ update_form|crispy }}
      <button type="submit" class="btn btn-outline-primary btn-block">Сохранить</button>
    </form>
    </p>
    <p>
      <a href="{% url 'admin:products' category.pk %}" class="btn btn-outline-secondary btn-block" role="button"
        aria-pressed="true">К списку продуктов</a>
    </p>
  </div>
</div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<p>
<div class="row justify-content-end">
  <div class="col-2">
    <a href="{% url 'admin:product_create' category.pk %}" class="btn btn-outline-secondary btn-sm" role="button"
      aria-pressed="true"><i class="fa fa-plus" aria-hidden="true"></i> Добавить</a>
  </div>
</div>
</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Фото</th>
      <th scope="col">Название</th>
      <th scope="col">К описанию</th>
      <th scope="col">Цена (руб.)</th>
      <th scope="col">Количество</th>
      <th scope="col" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for object in objects %}
    <tr id="{{ object.pk }}" {% if not object.is_active %}style="opacity: 30%;" {% endif %}>
      <th scope="row">{{ object.pk }}</th>
      <td>
        <img src="{{ media_url }}{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}"
          style="max-width: 100px;">
      </td>
      <td>{{ object.name|title }}</td>
      <td><a href="{% url 'admin:product_read' object.pk %}"><i class="fa fa-angle-right" aria-hidden="true"></i>
          Подробнее</a></td>
      <td>{{ object.price }}</td>
      <td>{{ object.quantity }}</td>
      <td><a href="{% url 'admin:product_update' object.pk %}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
      </td>
      <td><a href="{% url 'admin:product_delete' object.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
<p>
<div class="row justify-content-center">
  <div class="col-6">
    <h3>
      Уверены, что хотите удалить {{ user_to_delete.username }} {% if user_to_delete.first_name %}
      ({{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
      {{ user_to_delete.last_name|title }}
      {% endif %})
      {% endif %}?
    </h3>
    <form action="{% url 'admin:user_delete' user_to_delete.pk %}" method="post">
      {% csrf_token %}
      <p>
      <div class="row justify-content-around">
        <div class="col-5">
          <a href="{% url 'admin:users' %}" class="btn btn-outline-secondary btn-block"
            role="button" aria-pressed="true">Отмена</a>
        </div>
        <div class="col-5">
          <button type="submit" class="btn btn-outline-danger btn-block">Удалить</button>
        </div>
      </div>
      </p>
    </form>
  </div>
</div>
</p>
{% endblock content %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-7">
    <p>
    <form method="post">
      {% csrf_token %}
      {{ update_form|crispy }}
      <button type="submit" class="btn btn-outline-primary btn-block">Сохранить</button>
    </form>
    </p>
    <p>
      <a href="{% url 'admin:users' %}" class="btn btn-outline-secondary btn-block" role="button" aria-pressed="true">К
        списку пользователей</a>
    </p>
  </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<p>
<div class="row justify-content-end">
  <div class="col-2">
    <a href="{% url 'admin:user_create' %}" class="btn btn-outline-secondary btn-sm" role="button"
      aria-pressed="true"><i class="fa fa-plus" aria-hidden="true"></i> Добавить</a>
  </div>
</div>
</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Роль</th>
      <th scope="col">Логин</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Возраст</th>
      <th scope="col">Email</th>
      <th scope="col" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr id="{{ object.pk }}" {% if not object.is_active %}style="opacity: 30%;" {% endif %}>
      <th scope="row">{{ object.pk }}</th>
      <td>{% if object.is_superuser %}администратор{% else %}пользователь{% endif %}</td>
      <td>{{ object.username }}</td>
      <td>{{ object.first_name|title }}</td>
      <td>{{ object.last_name|title }}</td>
      <td>{{ object.age }}</td>
      <td>{{ object.email }}</td>
      <td><a href="{% url 'admin:user_update' object.pk %}"><i class="fa fa-pencil" aria-hidden="true"></i></a></td>
      <td>
        {% if not object.is_superuser %}
        <a href="{% url 'admin:user_delete' object.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}