best_shop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, re_path

import mainapp.views as mainapp
# import ordersapp.views as orders

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^products/", include("mainapp.urls", namespace="products")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    path("", include("social_django.urls", namespace="social")),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    re_path(r"^order/", include("ordersapp.urls", namespace="ordersapp")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.products, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.products, name="category"),
    re_path(r"^product/(?P<pk>\d+)/$", mainapp.product, name="product"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.products, name="page"),
]

ordersapp/urls.py
from django.urls import  path

import ordersapp.views as ordersapp
from ordersapp.apps import OrdersappConfig

app_name = OrdersappConfig.name

urlpatterns = [
    path("", ordersapp.OrederListView.as_view(), name="orders_list"),
    path("create/", ordersapp.OrederCreateView.as_view(), name="order_create"),
    path("read/<int:pk>/", ordersapp.OrderDetailView.as_view(), name="order_read"),
    path("edit/<int:pk>/", ordersapp.OrederUpdateView.as_view(), name="order_update"),
    path("delete/<int:pk>/", ordersapp.OrderDeleteView.as_view(), name="order_delete"),
    path("complete/<int:pk>/", ordersapp.order_forming_complete, name="order_forming_complete"),
]

ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    FORMING = "FM"
    SEND_TO_PROCEED = "STP"
    PROCEED = "PRD"
    PAID = "PD"
    READY = "PDY"
    CHANCEL = "CNC"
    ORDER_STATUS = (
        (FORMING, "Формируется"),
        (SEND_TO_PROCEED, "Отправлен на обработку"),
        (PROCEED, "Обработан"),
        (PAID, "Оплачен"),
        (READY, "Готов к выдаче"),
        (CHANCEL, "Отменено")
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="пользователь")
    status = models.CharField(max_length=3, choices=ORDER_STATUS, default=FORMING, verbose_name="статус")
    is_active = models.BooleanField(default=True, verbose_name="активен")
    created = models.DateTimeField(auto_now_add=True, verbose_name="дата создания заказа")
    updated = models.DateTimeField(auto_now=True, verbose_name="дата обновления заказа")

    def get_total_quantity(self):
        "return total quantity for user"
        _items = self.orderitems.select_related()
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    def get_total_cost(self):
        "return total cost for user"
        _items = self.orderitems.select_related()
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="Заказ", related_name="orderitems")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")

    @property
    def product_cost(self):
        "return cost of all products this type"
        return self.product.price * self.quantity


    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

ordersapp/forms.py
from django import forms

from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = Order
        fields = "__all__"



class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = OrderItem

        fields = "__all__"

ordersapp/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


class OrederListView(ListView):
    model = Order
    template_name = "ordersapp/orders_list.html"

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrederCreateView(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy("ordersapp:orders_list")
    template_name = "ordersapp/order_form.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            busket_items = Basket.get_items(user=self.request.user)
            if len(busket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(busket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = busket_items[num].product
                    form.initial['quantity'] = busket_items[num].quantity
                    form.initial['price'] = busket_items[num].product.price
                busket_items.delete()
            else:
                formset = OrderFormSet()
        data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
        if self.object.get_total_cost() == 0:
            self.object.delete()


        super().form_valid(form)
        return HttpResponseRedirect(reverse('ordersapp:order_update', args=[self.object.pk]))


class OrederUpdateView(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy("ordersapp:orders_list")
    template_name = "ordersapp/order_form.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
            # for form in formset.forms:
            #     form.initial['price'] = form.instance.product.price
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                product = Product.objects.filter(pk=form.instance.product_id)
                if product:
                    form.initial['price'] = product.first().price
        data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        super().form_valid(form)
        return HttpResponseRedirect(reverse('ordersapp:order_update', args=[self.object.pk]))


class OrderDetailView(DetailView):
    model = Order


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("ordersapp:orders_list")


def order_forming_complete(requesr, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SEND_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse("ordersapp:orders_list"))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity = instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.product.save()

@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()

ordersapp/templates/ordersapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
       {% block title %}
           {{ title|title }}
       {% endblock %}
   </title>
   {% block css %}
       <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
       <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
   {% endblock %}
   {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/orders_scripts.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
   {% endblock %}
</head>
<body>
  <div class="order_container">
       {% block content %}

       {% endblock %}

  </div>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load staticfiles %}

{% load mail_to %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img src="{{ item.product.image|media_folder_products }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load staticfiles %}


{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}

                               <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {% if field.name == "price" %}
                                    {% if field.value%}
                                    <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                        {{ field.value }}
                                    </span>
                                    {% endif %}
                               {% else %}
                                    {{ field }}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'ordersapp/includes/inc_order_actions.html' %}
       </form>
   </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}


{% block content %}
<p class="h2 text-center">
    Ваши заказы, уважаемый
    {% if user.first_name %}{{ user.first_name|title }}{% else %}{{ "пользователь"|capfirst }}{% endif %}
</p>
<p>
<div class="row justify-content-between">
    <div class="col-2">
        <a href="{% url 'main' %}" class="btn btn-sm btn-outline-secondary col-12" role="button"><i
                class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> {{ "на главную"|capfirst }}</a>
    </div>
    <div class="col-2">
        <a href="{% url 'ordersapp:order_create' %}" class="btn btn-sm btn-outline-success col-12" role="button"><i
                class="fa fa-plus" aria-hidden="true"></i> {{ "новый заказ"|capfirst }}</a>
    </div>
</div>
</p>
<p>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
            <th colspan="3">Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        {% if item.is_active %}
        <tr>
            <th scope="row">{{ item.pk }}</th>
            <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
            <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
            <td>{{ item.get_status_display }}</td>
            <td><a href="{% url 'ordersapp:order_read' item.pk %}" data-toggle="tooltip" data-placement="top"
                    title="Просмотр деталей"><i class="fa fa-list-alt" aria-hidden="true"></i></a></td>
            <td>
                {% if item.status == 'FM' %}
                <a href="{% url 'ordersapp:order_update' item.pk %}" data-toggle="tooltip" data-placement="top"
                    title="Редактировать"><i class=" fa fa-pencil" aria-hidden="true"></i></a>
                {% endif %}
            </td>
            <td>
                {% if item.status == 'FM' %}
                <a href="{% url 'ordersapp:order_delete' item.pk %}" data-toggle="tooltip" data-placement="top"
                    title="Удалить"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
</p>
{% endblock content %}

ordersapp/templates/ordersapp/orders_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}


{% block content %}
   <div class="h2 text-center head">
       Ваши заказы, 
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'main' %}">
           на главную
       </a>
   </button>
       <button class="btn btn-default btn-round">
           <a href="{% url 'ordersapp:order_create' %}">
               новый
           </a>
       </button>
{% endblock %}